import { useTranslation } from 'next-i18next'
import { getStaticPaths, makeStaticProps } from '../../lib/getStatic'
import Link from 'next/link'
import Head from 'next/head'

const Homepage = () => {
  const { t } = useTranslation(['common', 'footer', '404'])

  return (
    <>
    <Head>
      <title>{t('title')}</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
      <main>
        <h1>{t('h1')}</h1>
        <div>
          <Link href="/">
            <button type="button">{t('common:back-to-home')}</button>
          </Link>
        </div>
      </main>
      <footer>
        <p>{t('footer:description')}</p>
        <button>{t('footer:change-locale')}</button>
      </footer>
    </>
  )
}

export default Homepage

const getStaticProps = makeStaticProps(['404', 'common', 'footer'])
export { getStaticPaths, getStaticProps }
